todo/profiles/urls.py
from django.conf.urls import patterns, include, url
from django.core.urlresolvers import reverse_lazy

from . import views

urlpatterns = patterns('',
    url(r'^register/$', views.RegistrationView.as_view(), name='register'),
    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'profiles/login.html'}, name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': reverse_lazy('profiles:login')}, name='logout'),
    url(r'^password_change/$', 'django.contrib.auth.views.password_change', {'template_name': 'profiles/password_change.html', 'post_change_redirect': reverse_lazy('profiles:password_change_done')}, name='password_change'),
    url(r'^password_change/done/$', views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    url(r'^password_reset/$', 'django.contrib.auth.views.password_reset', {'template_name': 'profiles/password_reset.html', 'email_template_name': 'profiles/password_reset_email.html', 'subject_template_name': 'profiles/password_reset_subject.txt', 'post_reset_redirect': reverse_lazy('profiles:password_reset_done')}, name='password_reset'),
    url(r'^password_reset/done/$', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    url(r'^password_reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', 'django.contrib.auth.views.password_reset_confirm', {'template_name': 'profiles/password_reset_confirm.html', 'post_reset_redirect': reverse_lazy('profiles:password_change_done')}, name='password_reset_confirm'),
)

todo/todo/urls.py
from django.conf.urls import patterns, include, url

# from profiles.api import UserResource
from tasks.api import TaskResource

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'todo.views.home', name='home'),
    # url(r'^todo/', include('todo.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('tasks.urls', namespace='tasks')),
    url(r'^', include('profiles.urls', namespace='profiles')),
    url(r'^api/tasks/', include(TaskResource.urls())),
)

todo/profiles/models.py
from django.conf import settings
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser
from django.db import models

class UserManager(BaseUserManager):
    def create_user(self, email, name, password):
        """Creates and saves a user with a given email, name, and password."""
        if not email:
            raise ValueError("Email is required.")

        if not name:
            raise ValueError("Name is required.")

        if not password:
            raise ValueError("Password is required.")

        user = self.model(
            email=self.normalize_email(email),
            name=name
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, name, password):
        """Creates and saves a superuser with a given email, name, and password."""
        user = self.create_user(
            email=self.normalize_email(email),
            name=name,
            password=password
        )

        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)

        return user

class User(AbstractBaseUser):
    email = models.EmailField(
        max_length=255,
        unique=True,
        db_index=True
    )
    name = models.CharField(max_length=255)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name']

    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)

    objects = UserManager()

    def get_full_name(self):
        return self.name

    def get_short_name(self):
        return self.name.split()[0]

    def __unicode__(self):
        return self.email

class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL)
    timezone = models.CharField(max_length=50)

    def __unicode__(self):
        return self.user.email

todo/profiles/forms.py
from django import forms
from django.contrib.auth import get_user_model

import pytz

from .models import Profile

class RegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    timezone = forms.ChoiceField(initial='', choices=[(tz, tz) for tz in pytz.common_timezones])

    class Meta:
        model = get_user_model()
        fields = ('email', 'name', 'password')

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
            profile = Profile(user=user, timezone=self.cleaned_data['timezone'])
            profile.save()
        return user

todo/profiles/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, get_user_model, login
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse, reverse_lazy
from django.http import HttpResponseRedirect
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_control
from django.views.generic.base import View
from django.views.generic.edit import CreateView

from .forms import RegistrationForm
from .models import Profile

class LoginRequiredMixin(object):
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)

class CacheControlMixin(object):
    @method_decorator(cache_control(must_revalidate=True, no_cache=True, no_store=True))
    def dispatch(self, request, *args, **kwargs):
        return super(CacheControlMixin, self).dispatch(request, *args, **kwargs)

class RegistrationView(CreateView):
    model = get_user_model()
    form_class = RegistrationForm
    template_name = 'profiles/register.html'
    success_url = reverse_lazy('tasks:index')

    def form_valid(self, form):
        redirect = super(RegistrationView, self).form_valid(form)
        username = form.cleaned_data['email']
        password = form.cleaned_data['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(self.request, user)
        return redirect

class PasswordChangeDoneView(View):
    def get(self, request, *args, **kwargs):
        messages.success(request, "Password successfully changed.")
        return HttpResponseRedirect(reverse('tasks:index'))

class PasswordResetDoneView(View):
    def get(self, request, *args, **kwargs):
        messages.success(request, "Password has been reset. Check your email for further steps.")
        return HttpResponseRedirect(reverse('profiles:login'))

todo/profiles/templates/profiles/login.html
{% if messages %}
    {% for message in messages %}
        <p>{{ message }}</p>
    {% endfor %}
{% endif %}
<form method="POST" action="{% url 'profiles:login' %}">
    {% csrf_token %}
    {% if form.errors %}
        <p>No matching email or password. Please try again.</p>
    {% endif %}
    {% for field in form %}
        {% if field.errors %}
            {% for error in field.errors %}
                <p>{{ error }}</p>
            {% endfor %}
        {% endif %}
        <p>{{ field.label_tag }} {{ field }}</p>
    {% endfor %}
    <input type="hidden" name="next" value="{{ next }}" />
    <input type="submit" value="Login" />
</form>

todo/profiles/templates/profiles/password_change.html
<form method="POST" action="{% url 'profiles:password_change' %}">
    {% csrf_token %}
    {% if form.errors %}
        {{ form.errors }}
    {% endif %}
    {% for field in form %}
        <p>{{ field.label_tag }} {{ field }}</p>
    {% endfor %}
    <input type="hidden" name="next" value="{{ next }}" />
    <input type="submit" value="Submit" />
</form>

todo/profiles/templates/profiles/password_reset.html
<form method="POST" action="{% url 'profiles:password_reset' %}">
    {% csrf_token %}
    {% if form.errors %}
        {{ form.errors }}
    {% endif %}
    {% for field in form %}
        <p>{{ field.label_tag }} {{ field }}</p>
    {% endfor %}
    <input type="hidden" name="next" value="{{ next }}" />
    <input type="submit" value="Submit" />
</form>

todo/profiles/templates/profiles/password_reset_confirm.html
<form method="POST" action="{% url 'profiles:password_reset_confirm' %}">
    {% csrf_token %}
    {% if form.errors %}
        {{ form.errors }}
    {% endif %}
    {% for field in form %}
        <p>{{ field.label_tag }} {{ field }}</p>
    {% endfor %}
    <input type="hidden" name="next" value="{{ next }}" />
    <input type="submit" value="Submit" />
</form>

todo/profiles/templates/profiles/password_reset_email.html
Someone asked for password reset for email {{ email }}. Follow the link below:
{{ protocol}}://{{ domain }}{% url 'profiles:password_reset_confirm' uidb64=uid token=token %}

todo/profiles/templates/profiles/register.html
{% load staticfiles %}
<form id="register" action="" method="POST">
    {% csrf_token %}
    {% for field in form %}
        <p>{{ field.errors }}</p>
        <p>{{ field.label_tag }} {{ field }}</p>
    {% endfor %}
    <input type="submit" value="Sign Up" />
</form>
<script src="{% static 'js/jquery.min.js' %}"></script>
<script type="text/javascript" src="http://cdn.bitbucket.org/pellepim/jstimezonedetect/downloads/jstz-1.0.4.min.js"></script>
<script type="text/javascript">
    var timezone = jstz.determine().name();
    $('form#register select[name="timezone"]').val(timezone);
</script>